[package]
name = "idol_api"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.177", features = ["derive"] }
glam = "0.24.1"
bytes = "1.4.0"
nanoid = "0.4.0"
axum = "0.6.19"
