[package]
name = "idol_api"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { workspace = true, features = ["derive"] }
glam = { workspace = true }
bytes = { workspace = true }
nanoid = { workspace = true }
axum = { workspace = true }
