[package]
name = "bevy_vrm"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy = "0.11.0"
anyhow = "1.0.72"
gltf = "1.2.0"
bevy_gltf = "0.11.0"
serde = "1.0.178"
thiserror = "1.0.44"
base64 = "0.21.2"
serde_json = "1.0.104"
percent-encoding = "2.3.0"
bitflags = "2.3.3"
